name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"   # 07:00 sáng VN mỗi ngày

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: "waka"
          TIME_RANGE: "all_time"   # chính xác
          SHOW_TITLE: "true"
          LANG_COUNT: "5"
          SHOW_TIME: "true"
          SHOW_TOTAL: "true"
          STOP_AT_OTHER: "true"
          CODE_LANG: "txt"
          BLOCKS: "⣀⣄⣤⣦⣶⣷⣿"
          TARGET_BRANCH: "main"
          TARGET_PATH: "README.md"
          COMMIT_MESSAGE: "chore: update WakaTime stats"
