name: WakaTime (custom date range)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"   # 00:00 UTC = 07:00 sáng VN mỗi ngày

permissions:
  contents: write

env:
  START_DATE: "2025-08-15"      # <<< đổi ngày bắt đầu ở đây nếu muốn
  LANG_COUNT: "5"               # số ngôn ngữ hiển thị
  SECTION_NAME: "waka"          # phải trùng với comment trong README
  BLOCKS: "⣀⣄⣤⣦⣶⣷⣿"   # thanh tiến độ
  WIDTH: "28"                   # độ dài thanh tiến độ (ký tự)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure secret exists
        run
